flux_path: "/root/autodl-tmp/qyt/hfd_model"
dtype: "bfloat16"

model:
  union_cond_attn: true
  add_cond_attn: false
  latent_lora: false
  use_sep: false

  # Semantic conditioning configuration (Cross-Attention Mode)
  use_semantic_conditioning: true
  semantic_mode: "cross_attention"       # Options: "cross_attention" or "pixel_fusion"
  semantic_num_layers: 1                 # Number of cross-attention layers
  semantic_num_heads: 8                  # Number of attention heads

train:
  batch_size: 4
  accumulate_grad_batches: 1
  dataloader_workers: 4
  save_interval: 1000
  sample_interval: 1000
  max_steps: -1
  gradient_checkpointing: true
  save_path: "runs"

  condition_type: "vis2ir_cross_attn"
  dataset:
    type: "vis2ir_semantic"
    path: "/root/autodl-tmp/qyt_1/dataset/pid_llvip_dataset.parquet"
    condition_size: 512
    target_size: 512
    image_size: 512
    padding: 8
    drop_text_prob: 0.1
    drop_image_prob: 0.0
    include_semantic: true
    semantic_column: panoptic_img

  wandb:
    project: "Vis2IR-CrossAttention"

  lora_config:
    r: 32
    lora_alpha: 32
    init_lora_weights: "gaussian"
    target_modules: "(.*x_embedder|.*(?<!single_)transformer_blocks\\.[0-9]+\\.norm1\\.linear|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_k|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_q|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_v|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_out\\.0|.*(?<!single_)transformer_blocks\\.[0-9]+\\.ff\\.net\\.2|.*single_transformer_blocks\\.[0-9]+\\.norm\\.linear|.*single_transformer_blocks\\.[0-9]+\\.proj_mlp|.*single_transformer_blocks\\.[0-9]+\\.proj_out|.*single_transformer_blocks\\.[0-9]+\\.attn.to_k|.*single_transformer_blocks\\.[0-9]+\\.attn.to_q|.*single_transformer_blocks\\.[0-9]+\\.attn.to_v|.*single_transformer_blocks\\.[0-9]+\\.attn.to_out)"

  optimizer:
    type: "Prodigy"
    params:
      lr: 1
      use_bias_correction: true
      safeguard_warmup: true
      weight_decay: 0.01
